Singular links ula 1501
singular-labs/unreal-engine-sdk pull request #5
Opened 2021-07-08 05:02 UTC by tapasyat

2021-07-08 08:48 UTC, eyalsingular requested changes
Looks like most of the heavy lifting is behind us which is great.
My question is how do they register to the singular links delegate?
Do they need to init the Singular Delegate themselves?
If so, i think we should init it in the configure method and then add a register method before the init.

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
> +#include "UObject/UObjectIterator.h"
Where do we use it?

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
> +#import <AppTrackingTransparency/ATTrackingManager.h>
why do we need it?

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
> +        if (env->IsSameObject(linkParams, NULL))
nice

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
>  jobject TmapToJNIMap(TMap<FString, FString> tmap)
line break needed

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
> +        if (jDeeplink)
in C++ we need to explicitly compare to null

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
> +        if (jPassthrough)
same here

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
> +        for (TObjectIterator<USingularDelegates> Itr; Itr; ++Itr) {
you can use the BroadcastDDLHandler method instead of the code here

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
> +
remove line

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
> +    singularConfig.singularLinksHandler = ^(SingularLinkParams * params) {
add line break before

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
> +void BroadcastDDLHandler(FSingularLinkParams params) {
Please change the name of the method, it's not only for DDL, it's for Singular Links, in general we need to change everything with DDL to SingularLinks

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
> +    };
line break

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Singular_UPL.xml
> +        config.withSingularLink(getIntent(), new SingularUeLinkHandler());
did you test in all scenarios? 
1. cold start
2. open from background

You should test with 2 different links, to make sure we always take the latest intent, my concern is that on open from background it will take the older intent

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Public/SingularDelegates.h
> +DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FSingularDDLHandler, const FSingularLinkParams&, LinkParams);
Let's change the name to FSingularLinkHandler

2021-07-08 08:48 UTC, eyalsingular commented on SingularSDK/Source/SingularSDK/Public/SingularDelegates.h
> +    FSingularDDLHandler SingularDDLHandler;
Let's change the name to FSingularLinkHandler

2021-07-11 20:04 UTC, netazinger commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
> +        // We register for only here because we don't it to handle cold opens.
fix comment

2021-07-11 20:11 UTC, netazinger commented on SingularSDK/Source/SingularSDK/Private/SingularSDKBPLibrary.cpp
> +    singularApiKey = apiKey;
maybe add a comment for updating static vars and why

2021-07-11 20:13 UTC, netazinger approved these changes

2021-07-11 20:20 UTC, eyalsingular approved these changes

2021-07-11 20:20 UTC, merged